#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/*  */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */
//#define L10N_LANGUAGE      EN
#define L10N_LANGUAGE			RU
#define ARDUINO_ESP32S3_DEV  
#define SSD1322_GRAYSCALE         true
#define DSP_MODEL      DSP_SSD1322
#define IR_PIN		    8
#define TFT_RST		    6
#define I2S_DOUT      17
#define I2S_BCLK      16
#define I2S_LRC       15
#define ENC_BTNR      40
#define ENC_BTNL      41
#define ENC_BTNB      42
#define ENC_INTERNALPULLUP      false

#define BITRATE_FULL true //---właczenie wskaznika BitrateFull
#define EXT_WEATHER true //---skrocone informacje pogodowe

#endif